Contoso.Apps.SportsLeague/ViewModels/Store/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Contoso.Apps.SportsLeague.Web.ViewModels
{
    public class CartViewModel
    {
        public IList<ViewModels.CartItemViewModel> CartItems { get; set; }
        public decimal OrderTotal { get; set; }
        public int ItemsTotal { get; set; }
    }
}

Contoso.Apps.SportsLeague/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Contoso.Apps.SportsLeague.Data.Models;
using Contoso.Apps.SportsLeague.Data.Logic;
using AutoMapper;
using Contoso.Apps.SportsLeague.Web.ViewModels;

namespace Contoso.Apps.SportsLeague.Web.Controllers
{
    public class CartController : Controller
    {
        private ProductContext db = new ProductContext();

        // GET: Cart
        public ActionResult Index()
        {
            var cartId = new Helpers.CartHelpers().GetCartId();
            var vm = new CartViewModel();
            using (ShoppingCartActions usersShoppingCart = new ShoppingCartActions(cartId))
            {
                var shoppingCartItems = usersShoppingCart.GetCartItems();
                var cartItemsVM = Mapper.Map<List<CartItemViewModel>>(shoppingCartItems);
                vm.CartItems = cartItemsVM;
                vm.ItemsTotal = usersShoppingCart.GetCount();
                vm.OrderTotal = usersShoppingCart.GetTotal();
            }
            //var shoppingCartItems = db.ShoppingCartItems.Include(c => c.Product);
            return View(vm);
        }

        public RedirectResult AddToCart(int productId)
        {
            var cartId = new Helpers.CartHelpers().GetCartId();
            using (ShoppingCartActions usersShoppingCart = new ShoppingCartActions(cartId))
            {
                usersShoppingCart.AddToCart(productId);
            }
            return Redirect("Index");
        }

        // GET: Cart/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.ShoppingCartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // GET: Cart/Create
        public ActionResult Create()
        {
            ViewBag.ProductId = new SelectList(db.Products, "ProductID", "ProductName");
            return View();
        }

        // POST: Cart/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemId,CartId,Quantity,DateCreated,ProductId")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                db.ShoppingCartItems.Add(cartItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductId = new SelectList(db.Products, "ProductID", "ProductName", cartItem.ProductId);
            return View(cartItem);
        }

        // GET: Cart/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.ShoppingCartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductId = new SelectList(db.Products, "ProductID", "ProductName", cartItem.ProductId);
            return View(cartItem);
        }

        // POST: Cart/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemId,CartId,Quantity,DateCreated,ProductId")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cartItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductId = new SelectList(db.Products, "ProductID", "ProductName", cartItem.ProductId);
            return View(cartItem);
        }

        // GET: Cart/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.ShoppingCartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: Cart/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            CartItem cartItem = db.ShoppingCartItems.Find(id);
            db.ShoppingCartItems.Remove(cartItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Contoso.Apps.SportsLeague/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Contoso.Apps.Common.Extensions;
using Contoso.Apps.SportsLeague.Data.Models;

namespace Contoso.Apps.SportsLeague.Web.Controllers
{
    public class StoreController : Controller
    {
        private ProductContext db = new ProductContext();

        // GET: Store
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            var productsVm = Mapper.Map<List<ViewModels.ProductListViewModel>>(products);

            // Retrieve category listing:
            var categories = db.Categories.ToList();
            var categoriesVm = Mapper.Map<List<ViewModels.CategoryViewModel>>(categories);

            var vm = new ViewModels.StoreIndexViewModel
            {
                Products = productsVm,
                Categories = categoriesVm
            };

            return View(vm);
        }

        // GET: Store/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            var productVm = Mapper.Map<ViewModels.ProductViewModel>(product);

            // Find related products, based on the category:
            var relatedProducts = db.Products.Where(p => p.CategoryID == product.CategoryID && p.ProductID != product.ProductID).ToList();
            var relatedProductsVm = Mapper.Map<List<ViewModels.ProductListViewModel>>(relatedProducts);

            // Retrieve category listing:
            var categories = db.Categories.ToList();
            var categoriesVm = Mapper.Map<List<ViewModels.CategoryViewModel>>(categories);

            // Retrieve "new products" as a list of three random products not equal to the displayed one:
            var newProducts = db.Products.Where(p => p.ProductID != product.ProductID).ToList().Shuffle().Take(3);

            var newProductsVm = Mapper.Map<List<ViewModels.ProductListViewModel>>(newProducts);

            var vm = new ViewModels.StoreDetailsViewModel
            {
                Product = productVm,
                RelatedProducts = relatedProductsVm,
                NewProducts = newProductsVm,
                Categories = categoriesVm
            };

            return View(vm);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Contoso.Apps.SportsLeague/Views/Store/Details.cshtml
@model Contoso.Apps.SportsLeague.Web.ViewModels.StoreDetailsViewModel

@{
    ViewBag.Title = "Details";
}

@section HeaderOverlay {
<div class="button-wrapper">
    <div class="container">
        <div class="row">
            <a href="#" class="btn-content">Contoso Store</a>
        </div>
    </div>
</div>
}

<section class="store">
    <div class="container">
        <div class="row">
            <div class="wrapper clearfix">
                <aside class="content contact-wrap">
                    <div class="store-details-wrap clearfix">
                        <div class="fig-shop clearfix">
                            <aside class="fig-shop-img">
                                <img src="@Url.Content("~/Images/Products/")@Model.Product.ImagePath" alt="@Model.Product.ProductName">
                            </aside>
                            <aside class="fig-shop-content">
                                <h4 class="headline-lato">@Model.Product.ProductName</h4>
                                <h5>@String.Format("{0:c}", Model.Product.UnitPrice)</h5>
                                <p class="paragraph_opensans">@Model.Product.Description</p>
                                <div class="avilable-wrap clearfix">
                                    <div class="avl-wrp">
                                        <span>availability:</span>
                                        <span>available</span>
                                    </div>
                                    <a class="btn btn-small btn-red" href="@Url.Action("AddToCart", "Cart", new { productId = Model.Product.ProductID })">Add to cart</a>
                                </div>
                            </aside>
                        </div>
                        <div class="tab-shop clearfix">
                            <div role="tabpanel">
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist">
                                    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Description</a></li>
                                    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Additional information</a></li>
                                    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">reviews (12)</a></li>
                                </ul>

                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div role="tabpanel" class="tab-pane active" id="home">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.</div>
                                    <div role="tabpanel" class="tab-pane" id="profile">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </div>
                                    <div role="tabpanel" class="tab-pane" id="messages">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.</div>

                                </div>

                            </div>
                        </div>
                        <div class="shop-related clearfix">
                            <h6>related products</h6>
                            @foreach (var product in Model.RelatedProducts)
                            {
                                <div class="figure">
                                    <div class="item">
                                        <div class="item-img">
                                            <img src="@Url.Content("~/Images/Products/")@product.ImagePath" alt="Add @product.ProductName to cart" class="center-block">
                                            <div class="item-cart">
                                                <a href="@Url.Action("AddToCart", "Cart", new { productId = product.ProductID })">Add to cart</a>
                                            </div>
                                        </div>
                                        <div class="item-content">
                                            <div class="item-header clearfix">
                                                <span class="headline-lato">@product.ProductName</span>
                                                <span class="">@String.Format("{0:c}", product.UnitPrice)</span>
                                            </div>
                                            <p>
                                                <a href="@Url.Action("Details", "Store", new { id = product.ProductID })" class="btn trans-btn">Product Details</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                </aside>
                <aside class="sidebar">
                    <div class="item-menu">
                        <div class="item-menu-wrap">
                            <h5>Store categories</h5>
                            <ul class="category">
                                @foreach (var category in Model.Categories)
                                {
                                    <li><a href="#">@category.CategoryName</a></li>
                                }
                            </ul>
                        </div>

                    </div><!--  End of item-menu -->
                    <div class="item-menu ">
                        <div class="item-menu-wrap">
                            <h5>New items</h5>
                            @foreach (var product in Model.NewProducts)
                            {
                                <div class="item-wrap clearfix">
                                    <div class="item-fig">
                                        <img src="@Url.Content("~/Images/Products/")@product.ThumbnailPath" alt="@product.ProductName">
                                    </div>
                                    <div class="item-content">
                                        <h6><a href="@Url.Action("Details", "Store", new { id = product.ProductID })">@product.ProductName</a></h6>
                                        <p>@String.Format("{0:c}", product.UnitPrice)</p>
                                    </div>
                                </div>
                            }
                        </div>
                    </div><!--  End of item-menu -->
                    <div class="item-menu">
                        <div class="item-menu-wrap">
                            <h5>League Photos</h5>
                            <ul class="item-photo clearfix">
                                <li><a href=""><img src="@Url.Content("~/images/photo/lacrosse.jpg")" alt="image"></a></li>
                                <li><a href=""><img src="@Url.Content("~/images/photo/mens-volleyball.jpg")" alt="image"></a></li>
                                <li><a href=""><img src="@Url.Content("~/images/photo/rugby.jpg")" alt="image"></a></li>
                                <li><a href=""><img src="@Url.Content("~/images/photo/rugby-league.jpg")" alt="image"></a></li>
                                <li><a href=""><img src="@Url.Content("~/images/photo/soccer.jpg")" alt="image"></a></li>
                                <li><a href=""><img src="@Url.Content("~/images/photo/youth-baseball.jpg")" alt="image"></a></li>

                            </ul>
                        </div>
                    </div><!--  End of item-menu -->
                </aside>
            </div>

        </div>
    </div>
</section>

Contoso.Apps.SportsLeague/Views/Store/Index.cshtml
@model Contoso.Apps.SportsLeague.Web.ViewModels.StoreIndexViewModel

@{
    ViewBag.Title = "Index";
}

@section HeaderOverlay {
    <div class="button-wrapper">
        <div class="container">
            <div class="row">
                <a href="#" class="btn-content">Contoso Store</a>
            </div>
        </div>
    </div>
}

<!-- start of gallery -->
<section class="gallery-page-wrapper events">
    <div class="container">
        <ul class="menu-wrapper" id="menu">
            <li><a href="#menu" data-filter="*" class="headline-lato selected">select all</a></li>
            @foreach (var category in Model.Categories)
            {
                <li><a href="#menu" data-filter=".@category.CategoryID" class="headline-lato">@category.CategoryName</a></li>
            }
        </ul>
        <div class="row">
            <div class="wrapper isp-wrap">
                <div class="clearfix" id="list-item">
                    @foreach (var product in Model.Products)
                    {
                        <div class="figure @product.CategoryID">
                            <div class="item clearfix">
                                <a class="item-img" href="@Url.Action("Details", "Store", new { id = product.ProductID })">
                                    <img src="@Url.Content("~/Images/Products/")@product.ImagePath" alt="@product.ProductName" class="center-block">
                                </a>
                                <div class="item-content">
                                    <h4 class="headline-lato">@product.ProductName</h4>
                                    <div class="item-footer clearfix">
                                        <div class="footer-content">
                                            <div class="wrap clearfix">
                                                <span class="text-primary" style="font-size:1.5em">@String.Format("{0:c}", product.UnitPrice)</span>
                                            </div>
                                        </div>
                                        <div class="footer-button">
                                            <a class="btn trans-btn" href="@Url.Action("AddToCart", "Cart", new { productId = product.ProductID })">Add to cart</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

</section>